name: empty_prj
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.24


environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  archive: ^3.6.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  persian_datetime_picker: ^2.7.0
  process_run: ^1.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
