name: Flutter Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
    - name: Enable linux build
      run: flutter config --enable-linux-desktop
    - name: Build Flutter app for Linux
      run: flutter build linux
    - name: Archive Production Artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-release
        path: build/linux/x64/release/bundle
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/linux/x64/release/bundle/linux-release.zip
        tag: v1.0
        overwrite: true
        body: "This is first release"