name: Flutter Multi-Platform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
    - name: Enable linux build
      run: flutter config --enable-linux-desktop
    - name: Build Flutter app for Linux
      run: flutter build linux --release
    - name: Create .deb package
      run: |
        cd build/linux/x64/release/bundle
        mkdir -p DEBIAN
        echo "Package: my-flutter-app" > DEBIAN/control
        echo "Version: 1.0.${{ github.run_number }}" >> DEBIAN/control
        echo "Section: base" >> DEBIAN/control
        echo "Priority: optional" >> DEBIAN/control
        echo "Architecture: amd64" >> DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> DEBIAN/control
        echo "Description: My Flutter App" >> DEBIAN/control
        dpkg-deb --build . ../../../../../linux-release-bundle.deb
    - name: Compress release bundle
      run: |
        cd build/linux/x64/release/bundle
        zip -r ../../../../../linux-release-bundle.zip .
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-release
        path: |
          linux-release-bundle.zip
          linux-release-bundle.deb

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
    - name: Install dependencies
      run: flutter pub get
    - name: Build Windows app
      run: flutter build windows --release
    - name: Display build directory contents
      run: dir build\windows\x64\runner\Release
    - name: Compress release bundle
      run: |
        Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath windows-release-bundle.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: windows-release-bundle.zip

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Build Flutter app for Android
      run: flutter build apk --release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-release
        path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: [build-linux, build-windows, build-android]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Create version.json
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "{" > version.json
          echo "  \"version\": \"$VERSION\"," >> version.json
          echo "  \"linux_url\": \"https://github.com/${{ github.repository }}/releases/download/v$VERSION/linux-release-bundle.zip\"," >> version.json
          echo "  \"linux_deb_url\": \"https://github.com/${{ github.repository }}/releases/download/v$VERSION/linux-release-bundle.deb\"," >> version.json
          echo "  \"windows_url\": \"https://github.com/${{ github.repository }}/releases/download/v$VERSION/windows-release-bundle.zip\"," >> version.json
          echo "  \"android_url\": \"https://github.com/${{ github.repository }}/releases/download/v$VERSION/app-release.apk\"," >> version.json
          echo "  \"release_notes\": \"Release of the build from the commit ${{ github.sha }}.\"" >> version.json
          echo "}" >> version.json

      - name: Commit and push version.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.json
          git commit -m "Update version.json for release ${{ github.run_number }}"
          git push

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-release

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-release

      - name: Download Android artifact
        uses: actions/download-artifact@v4
        with:
          name: android-release

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v1.0.${{ github.run_number }} \
          --title "Release ${{ github.run_number }}" \
          --notes "Release of the build from the commit ${{ github.sha }}." \
          linux-release-bundle.zip linux-release-bundle.deb windows-release-bundle.zip app-release.apk
